import React, { useRef, useState, useEffect } from 'react';
import Countdown from '../components/Countdown/Countdown';
import Minter from '../components/Minter/Minter';
import HeroArea from '../components/HeroArea/HeroArea'

export default function Home() {
  const [minterOn, setMinterOn] = useState(true);

  return (
    <div>
        <title>Ementor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />

      <section style={{ backgroundColor: '#263c25' }}>


        <div className="custom_container">
          <section>
            <HeroArea/>
          </section>
          {minterOn ? <Minter /> : <Countdown />}
          <section>
          </section>
          <section>
          </section>
        </div>
      </section>
    </div>
  );
}
